device-management-toolkit/ui-toolkit-react

Jenkinsfile

added jenkinsfile.  copied from ui-toolkit and modified for react

ci: add jenkinsfile for scanning

---

package-lock.json
package.json

build(version): bump to v2.0.2

---

.github/workflows/ci.yml

closes AB#4318
Upgrade CI from Node 14.x to new LTS 16.x

ci(node): bump from 14.x to 16.x

---

.github/workflows/release.yml
.releaserc.json
package-lock.json
package.json

adds automated releases using semantic-release

ci(semantic-release): adds automated releases

---

.github/workflows/release.yml

ci(release.yml): fixes README.md reference

---

.github/commitlint.config.js
.github/workflows/semantic.yml

ci(lint): adds semantic checks to PRs

---

.github/workflows/ci.yml
jest.config.js
package-lock.json
package.json

ci(jest): add junit report

---

package.json

fixed Published version broken since 2.0.3 #390

fix: prepublish script now checks ./dist exists

---

package-lock.json
package.json

fix(peer-deps): correct the peer dependencies to react 16 from 18

---

.github/workflows/release.yml

fix: ci build process

---

.github/workflows/projectsSync.yaml

ci: add project sync to ui-toolkit-react

---

.github/workflows/azureBoardsSync.yml

ci: add azure board sync

---

.github/workflows/changelog.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release.yml
.github/workflows/semantic.yml

ci: update actions/checkout, update semantic PR

---

.github/workflows/ci.yml
.github/workflows/release.yml

ci: pin cycjimmy/semantic-release-action and actions/setup-node to v3

---

.github/workflows/ci.yml

ci: remove dist push

---

.github/workflows/ci.yml
.github/workflows/release.yml

ci: update to node 20

---

package-lock.json
package.json
src/reactjs/KVM/UI.tsx
src/reactjs/SerialOverLAN/Sol.tsx
src/test/helper/amtredirector1.ts

build: bump @open-amt-cloud-toolkit/ui-toolkit to v3.0.0

---

package-lock.json
src/reactjs/IDER/AttachDiskImage.tsx
src/reactjs/IDER/ider.tsx
src/reactjs/IDER/index.tsx
src/reactjs/KVM/index.tsx
src/reactjs/sample/sampleKVM.htm
src/test/attachDiskImage.spec.tsx
src/test/ider.spec.tsx
webpack.config.externals.js
webpack.config.prod.js

feat: adds IDER component

---

.github/workflows/release.yml
.releaserc.json

ci: update package.json during release

---

package-lock.json
package.json
src/reactjs/SerialOverLAN/Sol.tsx
src/test/terminal.test.tsx

build: replaced xterm with @xterm/xterm

---

.github/workflows/semantic.yml

ci: update permissions in semantic.yml

---

.github/workflows/release.yml

ci: update permissions for release.yml

---

.releaserc.json

ci: updated semantic release for changelog

---

.github/workflows/release.yml
README.md

ci: add @device-management-toolkit publishing for ui-toolkit-react

---

package-lock.json
package.json
src/reactjs/IDER/ider.tsx
src/reactjs/KVM/UI.tsx
src/reactjs/SerialOverLAN/Sol.tsx
src/test/helper/amtredirector1.ts
src/test/ider.spec.tsx

build(deps): update to @device-management-toolkit org for ui-toolkit

---

README.md
package-lock.json
package.json

build(deps): move to new npm org @device-management-toolkit/ui-toolkit

---

package-lock.json
package.json

build: revert package name until later date
